# Generated by Django 4.0.6 on 2022-08-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(default=None, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('max_people', models.PositiveIntegerField()),
            ],
        ),
    ]
