# Generated by Django 4.0.6 on 2022-08-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='password2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
